nelmio_api_doc:
    models: { use_jms: false }
    documentation:
        info:
            title: Recipe App
            description: App to manage stock and decision to prepare launch
            version: 1.0.0
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Value should be : Bearer {Access token eventually get by /api/login_check}'
                name: Authorization
                in: header
                default: 'Bearer '
        definitions:
            ListProductOutput:
                type: array
                items:
                    $ref: "#/definitions/ProductItemOutput"
            ProductItemOutput:
                type: object
                properties:
                    id:
                        type: integer
                        required: true
                    name:
                        type: string
                        required: true
                    typeProduct:
                        type: integer
                        required: true
                        description: Unique identifier for product type
            ListProductTypeOutput:
                type: array
                items:
                    $ref: "#/definitions/ProductTypeItemOutput"
            ProductTypeItemOutput:
                type: object
                properties:
                    id:
                        type: integer
                        required: true
                    names:
                        type: array
                        required: true
            AddProductOutput:
                type: object
                properties:
                    id:
                        type: integer
                        required: true
                    name:
                        type: string
                        required: true
                    slug:
                        type: string
                        required: true
                    typeProduct:
                        type: integer
                        required: true
                    typeQuantity:
                        type: integer
                        required: true
            ListTypeQuantityOutput:
                type: array
                items:
                    $ref: "#/definitions/QuantityTypeItemOutput"
            QuantityTypeItemOutput:
                type: object
                properties:
                    id:
                        type: integer
                        required: true
                    names:
                        type: array
                        required: true
            AddGroupInput:
                type: object
                properties:
                    name:
                        type: string
                        required: true
            GroupOutput:
                type: object
                properties:
                    id:
                        type: integer
                        required: true
                    name:
                        type: string
                        required: true
                    slug:
                        type: string
                        required: true
                    owner:
                        type: object
                        $ref: "#/definitions/UserOutput"
                    members:
                        type: array
                        items:
                            $ref: "#/definitions/UserOutput"
            UserOutput:
                type: object
                properties:
                    id:
                        type: integer
                        required: true
                    firstname:
                        type: string
                        required: true
                    lastname:
                        type: string
                        required: true
            StockOutput:
                type: array
                items:
                    $ref: "#/definitions/StockItemOutput"
            StockItemOutput:
                type: object
                properties:
                    id:
                        type: integer
                        required: true
                        description: Unique identifier of stock product
                    product:
                        type: object
                        $ref: "#/definitions/AddProductOutput"
                    quantity:
                        type: number
                        required: true
                        description: Quantity in stock


    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
            - ^/api/login_check