snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: '%env(resolve:REDIS_URL)%'
        doctrine:
            type: predis
            alias: doctrine
            dsn: '%env(resolve:REDIS_URL)%'
    doctrine:
        metadata_cache:
            client: doctrine
            entity_manager: default
            document_manager: default
        result_cache:
            client: doctrine
            entity_manager: default
        query_cache:
            client: doctrine
            entity_manager: default
