doctrine:
    orm:
        auto_generate_proxy_classes: false
        metadata_cache_driver: redis
        query_cache_driver: redis

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
