# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Domain/Model,Domain/DoctrineMigrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\UI\Actions\:
        resource: '../src/UI/Actions'
        tags: ['controller.service_arguments']

    App\Application\Subscribers\TimestampableSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    App\Application\Listeners\JWT\JWTAuthFailure:
        class: App\Application\Listeners\JWT\JWTAuthFailure
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_failure, method: onAuthenticationFailureResponse }

    App\Application\Listeners\JWT\JWTInvalid:
        class: App\Application\Listeners\JWT\JWTInvalid
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_invalid, method: onJWTInvalid }

    App\Application\Listeners\JWT\JWTNotFound:
        class: App\Application\Listeners\JWT\JWTNotFound
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_not_found, method: onJWTNotFound }

    App\Application\Listeners\JWT\JWTExpired:
        class: App\Application\Listeners\JWT\JWTExpired
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_expired, method: onJWTExpired }

    App\Application\Listeners\Doctrine\Model\TypeProductListener:
        class: App\Application\Listeners\Doctrine\Model\TypeProductListener
        tags:
            - { name: doctrine.orm.event_listener}

